<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');

$users = Data::get('users');
?>

<div class="container">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Username</th>
            <th scope="col">Banned</th>
            <th scope="col">Admin</th>
            <th scope="col">Initial Cards</th>
            <th scope="col">Control</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?=$user->id?></td>
                <td><?=$user->username?></td>
                <td><?=$user->isbanned == 0 ? 'No' : 'Yes'?></td>
                <td><?=$user->isadmin == 0 ? 'No' : 'Yes'?></td>
                <td><?=$user->cartasiniciais?></td>
                <td><a class="btn btn-dark ml-auto" href="<?=Url::toRoute('home/edit/', $user->id)?>">Edit</a></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<?php Layout::includeLayout('footer') ?>
