<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php 
	$utilizador = Data::get('utilizador');
	\Tracy\Debugger::barDump($utilizador, "Utilizador");
?>
<?php ErrMgr::attach($utilizador) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Edit Book</h1>
				</header>
				

					<div class="panel panel-default">
						<div class="panel-body">

                            <hr>


							<form class="form-horizontal" method="post" action="<?=Url::toRoute('home/updateProfile', $utilizador->id)?>">

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="username">Username:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" value="<?=$utilizador->username?>" class="form-control" required name="username" placeholder="Enter username">
                                        <?= ErrMgr::bind('username') ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="password">Password:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$utilizador->password?>" class="form-control" name="password" placeholder="Enter password">
                                        <?= ErrMgr::bind('password') ?>
                                    </div>
                                </div>


								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-default" type="submit">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>


				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>