<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
$game = Data::get('game');

Layout::includeLayout('header');
//var_dump($game->_playerHand);
$_playerHand = $game->_playerHand;
$_botHand = $game->_botHand;
$_playerPoints = $game->_playerPoints;
$_botPoints = $game->_botPoints;
$_playerTurn = $game->_playerTurn;
$_deck = $game->_deck;

?>

<ul>
    <li>
        <a href="<?=Url::toRoute('home/Reset')?>">Reset</a>
    </li>
    <li style="display: inline">
        Player Score: <?php echo $_playerPoints; ?>
    </li>
    <li style="display: inline; float: right;">
        Bot Score: <?= $_botPoints ?>
    </li>
    <li>
        Player Hand:
        <ul>
            <?php foreach ($_playerHand->_hand as $card) { ?>
                <!-- <li style="display: inline"> <?= $card->_identifier ?> </li> -->
                <img width="7%" src="<?=Asset::image('Cards/card' . $card->_identifier . '.png')?>" class="card" id="<?= $card->_identifier ?>">
            <?php } ?>
        </ul>
    </li>
    <li>
        Bot Hand:
        <ul>
            <?php foreach ($_botHand->_hand as $card) { ?>
                <!-- <li style="display: inline"> <?= $card->_identifier ?> </li> -->
                <img width="7%" src="<?=Asset::image('Cards/card' . $card->_identifier . '.png')?>" class="" id="<?= $card->_identifier ?>">
            <?php } ?>
        </ul>
    </li>
    <li>
        Deck:
        <ul>
            <?php foreach ($_deck->_deck as $card) { ?>
                <!-- <li style="display: inline"> <?= $card->_identifier ?> </li> -->
                <img width="7%" src="<?=Asset::image('Cards/card' . $card->_identifier . '.png')?>" class="" id="<?= $card->_identifier ?>">
            <?php } ?>
        </ul>
    </li>
</ul>

<script>
    $( document ).ready(function() {
        let canPlay = true;

        $('.card').click(function(){
            if (canPlay == false){
                return;
            }
            canPlay = false;
            //alert($(this).attr('id'));

            $.ajax({
                type: "POST",
                url: "GoFish",
                data: {
                    card:$(this).attr('id')//.replace(/\D/g,'')
                },
                success: function() {   
                    location.reload();  
                }
            });
        });
    });
</script>


<?php
Layout::includeLayout('footer')
?>
