<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
$game = Data::get('game');

Layout::includeLayout('header');
?>


<div class="container">
	<div class="row mt-2">
		<li>
			Player (<?= $game->getPlayerPoints() ?> Points):
		</li>
		<a class="btn btn-dark ml-auto" href="<?=Url::toRoute('home/Reset')?>">Reset</a>
		<div class="row col-12">
			<?php foreach ($game->getPlayerHand() as $card) { ?>
				<div class="col-6 col-sm-4 col-md-3 col-xl-2 mb-3 _card">
					<img class="player-card" src="<?=Asset::image('Cards/card' . $card->getIdentifier() . '.png')?>" alt="<?= $card->getIdentifier() ?>" data-card="<?= $card->getValue() ?>">
				</div>
			<?php } ?>
		</div>


		<li>
			Bot (<?= $game->getBotPoints() ?> Points):
		</li>
		<div class="row col-12">
			<?php foreach ($game->getBotHand() as $card) { ?>
				<div class="col-6 col-sm-4 col-md-3 col-xl-2 mb-3 _card">
					<img src="<?=Asset::image( $game->isDebug() ? 'Cards/card' . $card->getIdentifier() . '.png' : 'Cards/cardBack_red4.png' )?>" alt="Bot Card">
				</div>
			<?php } ?>
		</div>


		<li>
			Deck:
		</li>
		<div class="row col-12">
			<?php foreach ($game->getDeck() as $card) { ?>
				<div class="col-6 col-sm-4 col-md-3 col-xl-2 mb-3 _card">
					<img src="<?=Asset::image( $game->isDebug() ? 'Cards/card' . $card->getIdentifier() . '.png' : 'Cards/cardBack_red4.png' )?>" alt="Deck Cards">
				</div>
			<?php } ?>
		</div>
	</div>
</div>

<div class="modal fade" id="endmodal" tabindex="-1" role="dialog" aria-labelledby="endDialogLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="removeDialoglLabel">Game Finished</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				Congratulations, you won the game!
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">New Game</button>
			</div>
		</div>
	</div>
</div>

<script>
	window.addEventListener('load', function() {
		$( document ).ready(function() {
			let canPlay = true;

			$('.player-card').click(function(){
				if (canPlay == false){
					return;
				}
				canPlay = false;

				$.ajax({
					type: "POST",
					url: "play",
					data: {
						card: $(this).data('card')
					},
					success: function(data) {  
						<?= $game->isDebug() ? 'alert(data);' : ''?>
						location.reload();  
					}
				});
			});
		});
	}, false);
</script>


<?php
Layout::includeLayout('footer')
?>
