<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header');

$valid = Data::get('valid');

?>



    <body>
    <div id="login">
        <br>
        <h4 class="thin text-center">Sign in to your account</h4>
        <p class="text-center text-muted">Or click <a href="signup">HERE</a>, to create a new one</p>
        <br>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <?php if (!$valid) { ?>
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                Login Invalido!
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        <?php } ?>
                        <form method="post">
                            <div class="top-margin">
                                <label>Username/Email <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="Username">
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="Password">
                            </div>

                            <br>

                            <div class="col-lg-12 text-right">
                                <button class="btn btn-action" type="submit">Sign in</button>
                            </div>
                        </form>

                    <br><hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>


<?php Layout::includeLayout('footer') ?>