<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header') ?>

<?php 
	$utilizador = Data::get('utilizador');
	\Tracy\Debugger::barDump($utilizador, "Utilizador");
?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">My Account Settings</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							
							<form method="post" action="<?=Url::toRoute('home/show')?>">
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$utilizador->username?>" name="username" class="form-control">
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" value="<?=$utilizador->password?>" name="password" class="form-control">
								</div>
								<div class="top-margin">
									<label>Name <span class="text-danger">*</span></label>
									<input type="text" value="<?=$utilizador->nome?>" name="nome" class="form-control">
								</div>
                                <div class="top-margin">
                                    <label>Date of Birthday <span class="text-danger">*</span></label>
                                    <input type="date" value="<?=$utilizador->datanascimento?>" name="datanascimento" class="form-control">
                                </div>
								<div class="top-margin">
									<label>E-mail <span class="text-danger">*</span></label>
									<input type="text" value="<?=$utilizador->email?>" name="email" class="form-control">
								</div>

								<hr>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Edit</button>
									</div>
									
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>