<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

$isadmin = Data::get('isadmin');

Layout::includeLayout('header') ?>

<?php 
	$utilizador = Data::get('utilizador');
	\Tracy\Debugger::barDump($utilizador, "Utilizador");
?>


    <body>
    <div id="login">
        <br>
        <h4 class="thin text-center">My Profile</h4>
        <br>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form method="post">
                            <input readonly="true" type="hidden" class="form-control" name="id" value="<?=$utilizador->id?>">
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" class="form-control" name="username" value="<?=$utilizador->username?>">
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="password" value="<?=$utilizador->password?>">
                            </div>
                            <div class="top-margin">
                                <label>Name <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="nome" value="<?=$utilizador->nome?>">
                            </div>
                            <div class="top-margin">
                                <label>Date of Birthday <span class="text-danger">*</span></label>
                                <input type="date" name="datanascimento" class="form-control" value="<?=$utilizador->datanascimento?>">
                            </div>
                            <div class="top-margin">
                                <label>E-mail <span class="text-danger">*</span></label>
                                <input type="text" name="email" class="form-control" value="<?=$utilizador->email?>">
                            </div>
                            <?php if($isadmin === true){ ?>
                                <div class="top-margin">
                                    <label>Initial Hand Cards <span class="text-danger">*</span></label>
                                    <input type="number" name="cartasiniciais" class="form-control" value="<?=$utilizador->cartasiniciais?>">
                                </div>
                                <div class="top-margin">
                                    <label>Is Banned <span class="text-danger">*</span></label> <br />
                                    <input type="radio" name="isbanned" value="0" <?= ($utilizador->isbanned == 0) ? 'checked' : '' ?> > No<br />
                                    <input type="radio" name="isbanned" value="1" <?= ($utilizador->isbanned != 0) ?    'checked' : '' ?> > Yes<br />
                                </div>
                                <div class="top-margin">
                                    <label>Is Admin <span class="text-danger">*</span></label> <br />
                                    <input type="radio" name="isadmin" value="0" <?= ($utilizador->isadmin == 0) ? 'checked' : '' ?> > No<br />
                                    <input type="radio" name="isadmin" value="1" <?= ($utilizador->isadmin != 0) ?    'checked' : '' ?> > Yes<br />
                                </div>
                            <?php } ?>
                            <br>

                            <div class="col-lg-12 text-right">
                                <button class="btn btn-action" type="submit">Submit</button>
                            </div>
                        </form>

                        <br><hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>


<?php Layout::includeLayout('footer') ?>