<?php use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header') ?>


    <body>
    <div id="login">
        <br>
        <h4 class="thin text-center">Create new account</h4>
        <p class="text-center text-muted">Or click <a href="login">HERE</a>, if you already have one.</p>
        <br>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form method="post">
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="username">
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password">
                            </div>
                            <div class="top-margin">
                                <label>Name <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="nome">
                            </div>
                            <div class="top-margin">
                                <label>Date of Birthday <span class="text-danger">*</span></label>
                                <input type="date" class="form-control"  name="datanascimento">
                            </div>
                            <div class="top-margin">
                                <label>E-mail <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="email" >
                            </div>


                            <br>

                            <div class="col-lg-12 text-right">
                                <button class="btn btn-action" type="submit">Sign up</button>
                            </div>
                        </form>

                        <br><hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>




<?php Layout::includeLayout('footer') ?>