<?php use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header') ?>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">User access</li>
		</ol>

		<div class="row">

			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Sign up</h1>
				</header>

				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Create new account</h3>
							<p class="text-center text-muted">Lorem ipsum dolor sit amet, <a href="login">Login</a> adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio. </p>
							<hr>

                            <form method="post">
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input type="text" name="username" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="password"  name="password" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Name <span class="text-danger">*</span></label>
                                    <input type="text"  name="nome" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Date of Birthday <span class="text-danger">*</span></label>
                                    <input type="date" name="datanascimento" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>E-mail <span class="text-danger">*</span></label>
                                    <input type="text" name="email" class="form-control">
                                </div>

                                <hr>
                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Sign Up</button>
                                </div>

                                </div>
                            </form>
						</div>
					</div>

				</div>

			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>