<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header');

$users = Data::get('users');
?>

    <!-- container -->
    <div class="container">

        <h2>Top 10 Winners</h2>



        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Username</th>
                    <th scope="col">Wins</th>
                    <th scope="col">Games</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    $pos = 0;
                    foreach ($users as $user) {
                ?>
                    <tr>
                        <?php $pos++;?>
                        <th scope="row"><?=$pos?></th>
                        <td><?=$user->username?></td>
                        <td><?=$user->numerovitorias?></td>
                        <td><?=$user->numerojogos?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>




    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>