<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
$islogin = Data::get('islogin');
?>

<!DOCTYPE html>
<html lang="pt-PT">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>GoFish</title>
		
		<!-- Font Ubuntu Mono -->
		<link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono" rel="stylesheet">

		<!-- Font Awesome -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<!-- Stylesheet -->
		<link rel="stylesheet" type="text/css" href="<?= Asset::css('styles.css')?>">
	</head>
	<body>
		<!-- Navbar -->
		<header> 
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="<?=Url::toRoute('home/index')?>">GoFish</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
                        <?php if($islogin === true){ ?>
							<li class="nav-item">
								<a href="<?=Url::toRoute('home/index')?>" class="nav-link">Play</a>
							</li>
                        <?php } ?>
						<li class="nav-item">
							<a href="<?=Url::toRoute('home/stats')?>" class="nav-link">Stats</a>
						</li>
                        <?php if($islogin === true) { ?>
							<li class="nav-item">
								<a href="<?=Url::toRoute('home/profile')?>" class="nav-link">Profile</a>
							</li>
							<li class="nav-item">
								<a href="<?=Url::toRoute('home/logout')?>" class="nav-link">Logout</a>
							</li>
                        <?php }else { ?>
                            <li class="nav-item">
                                <a href="<?=Url::toRoute('home/logout')?>" class="nav-link">Sign in/ Sign Up</a>
                            </li>
                        <?php } ?>
					</ul>
				</div>
			</nav>
		</header>
