<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
$islogin = Data::get('islogin');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">


    <title>Go Fish</title>

    <?=AssetBundler::css()?>

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body class="home">
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="<?= URL::toRoute('home/index')?>"><img src="<?= Asset::image('gofish6.png')?>" width="25%" alt="GoFish"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">

                <?php
                    if($islogin === true){
                        ?>
                        <li><a class="btn" href="<?= URL::toRoute('home/GoFish') ?>">START FISHING</a></li>
                        <?php
                    }
                ?>
                <li><a class="btn" href="<?= URL::toRoute('home/stats') ?>">STATS</a></li>
                <?php
                    if($islogin === true) {
                        ?>
                        <li><a class="btn" href="<?= URL::toRoute('home/profile') ?>">SHOW PROFILE</a></li>
                        <li><a class="btn" href="<?= URL::toRoute('home/logout') ?>">LOG OUT</a></li>
                        <?php
                    }else {
                        ?>
                        <li><a class="btn" href="<?= URL::toRoute('home/login') ?>">SIGN IN / SIGN UP</a></li>
                        <?php
                    }
                ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->
<header id="head" class="secondary"></header>