<!doctype html>
<html lang="pt-PT">
<?php Layout::includeLayout('indexheader'); ?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


<?php
require '..\vendor\autoload.php';
use Carbon\Carbon;
?>

<h1>Plano de pagamentos</h1>
<p>Nome: <?php echo $_POST["nome"]?></p>
<p>Despesa: € <?php echo $_POST["despesas"]?></p>
<p>Valor a contrair: € <?php echo $_POST["credito"]?></p>
<p>Número de prestações: <?php echo $dossier -> getNumPrest() ?></p>
<p>Data do empréstimo: <?php echo Carbon::now()->toDateString()?></p><br>

<table border = "2">
    <tr>
        <th>NºPrest.</th>
        <th>Data</th>
        <th>Valor Prest.</th>
        <th>Valor em Dívida</th>
    </tr>

    <?php

    $pagamentos = $dossier -> getPlanoPagamentos();
    //$numPrest = $dossier -> getNumPrest();
    $numPrest = count($pagamentos);
    $cols = count($pagamentos[0]);
    for($row = 0; $row < $numPrest; $row++){
        echo '<tr>';
        echo '<td>'.($row+1).'</td>';
        for($col = 0; $col < $cols; $col++) {
            if($row == 0)
                $pagamentos [0][1] = round(($credito / $numPrest) + $credito*0.1, 2);
            echo '<td>'.$pagamentos[$row][$col].'</td>';
        }echo '</tr>';
    }
    ?>

</table>

</body>

<?php Layout::includeLayout('footer'); ?>

</html>